# players.py
# Lista svincolati (ordinata per ruolo e alfabetico).

PLAYERS = [
    "Audero - CRE (POR)",
    "Bijlow - GEN (POR)",
    "Calligaris - INT (POR)",
    "Cavlina - COM (POR)",
    "Christensen O. - FIO (POR)",
    "Ciocci - CAG (POR)",
    "Contini - NAP (POR)",
    "Corvi - PAR (POR)",
    "Ferrante - NAP (POR)",
    "Furlanetto - LAZ (POR)",
    "Gollini - ROM (POR)",
    "Israel - TOR (POR)",
    "Lezzerini - FIO (POR)",
    "Motta - LAZ (POR)",
    "Muric - SAS (POR)",
    "Nava - CRE (POR)",
    "Nicolas - PIS (POR)",
    "Nunziante - UDI (POR)",
    "Okoye - UDI (POR)",
    "Padelli - UDI (POR)",
    "Paleari - TOR (POR)",
    "Perilli - VER (POR)",
    "Pessina Mas. - BOL (POR)",
    "Pinsoglio - JUV (POR)",
    "Rinaldi - PAR (POR)",
    "Rossi F. - ATA (POR)",
    "Samooja - LEC (POR)",
    "Satalino - SAS (POR)",
    "Sava - UDI (POR)",
    "Scuffet - PIS (POR)",
    "Semper - PIS (POR)",
    "Sherri - CAG (POR)",
    "Silvestri - CRE (POR)",
    "Sommariva - GEN (POR)",
    "Sportiello - ATA (POR)",
    "Toniolo - VER (POR)",
    "Tornqvist - COM (POR)",
    "Torriani - MIL (POR)",
    "Turati - SAS (POR)",
    "Vasquez D. - ROM (POR)",
    "Vigorito - COM (POR)",
    "Zelezny - ROM (POR)",
    "Albiol - PIS (DIF)",
    "Arizala - UDI (DIF)",
    "Athekame - MIL (DIF)",
    "Barbieri - CRE (DIF)",
    "Bartesaghi - MIL (DIF)",
    "Belghali - VER (DIF)",
    "Bella-Kotchap - VER (DIF)",
    "Bernasconi - ATA (DIF)",
    "Bertola - UDI (DIF)",
    "Bianchetti - CRE (DIF)",
    "Bozhinov - PIS (DIF)",
    "Bradaric - VER (DIF)",
    "Britschgi - PAR (DIF)",
    "Cabal - JUV (DIF)",
    "Calabresi - PIS (DIF)",
    "Candè - SAS (DIF)",
    "Canestrelli - PIS (DIF)",
    "Caracciolo A. - PIS (DIF)",
    "Carboni F. - PAR (DIF)",
    "Casale - BOL (DIF)",
    "Ceccherini - CRE (DIF)",
    "Celik - ROM (DIF)",
    "Cham - VER (DIF)",
    "Circati - PAR (DIF)",
    "Coppola F. - PIS (DIF)",
    "Coulibaly W. - SAS (DIF)",
    "Cuadrado - PIS (DIF)",
    "De Vrij - INT (DIF)",
    "Dembelè A. - TOR (DIF)",
    "Denoon - PIS (DIF)",
    "Diego Carlos - COM (DIF)",
    "Doig - SAS (DIF)",
    "Dossena - CAG (DIF)",
    "Ebosse - VER (DIF)",
    "Ehizibue - UDI (DIF)",
    "Estupinan - MIL (DIF)",
    "Faye - CRE (DIF)",
    "Floriani Mussolini - CRE (DIF)",
    "Folino - CRE (DIF)",
    "Fortini - FIO (DIF)",
    "Frese - VER (DIF)",
    "Gallo - LEC (DIF)",
    "Goglichidze - UDI (DIF)",
    "Goldaniga - COM (DIF)",
    "Gutierrez - NAP (DIF)",
    "Heggem - BOL (DIF)",
    "Helland - BOL (DIF)",
    "Hermoso - ROM (DIF)",
    "Holm - BOL (DIF)",
    "Hysaj - LAZ (DIF)",
    "Idrissi R. - CAG (DIF)",
    "Idzes - SAS (DIF)",
    "Ismajli - TOR (DIF)",
    "Jean - LEC (DIF)",
    "Joao Mario - JUV (DIF)",
    "Juan Jesus - NAP (DIF)",
    "Kabasele - UDI (DIF)",
    "Kamara H. - UDI (DIF)",
    "Kelly L. - JUV (DIF)",
    "Kolasinac - ATA (DIF)",
    "Kouadio - FIO (DIF)",
    "Kouassi - LEC (DIF)",
    "Lamptey - FIO (DIF)",
    "Lirola - VER (DIF)",
    "Lucumì - BOL (DIF)",
    "Luperto - CAG (DIF)",
    "Marcandalli - GEN (DIF)",
    "Marianucci - NAP (DIF)",
    "Maripan - TOR (DIF)",
    "Marusic - LAZ (DIF)",
    "Masina - TOR (DIF)",
    "Mateus Lusuardi - PIS (DIF)",
    "Mazzocchi - NAP (DIF)",
    "Mina - CAG (DIF)",
    "Miranda J. - BOL (DIF)",
    "Moreno Alb. - COM (DIF)",
    "Muharemovic - SAS (DIF)",
    "Ndaba - LEC (DIF)",
    "Ndiaye - PAR (DIF)",
    "Nelsson - VER (DIF)",
    "Nkounkou - TOR (DIF)",
    "Norton-Cuffy - GEN (DIF)",
    "Obert - CAG (DIF)",
    "Obrador - TOR (DIF)",
    "Odenthal - SAS (DIF)",
    "Odogu - MIL (DIF)",
    "Ostigard - GEN (DIF)",
    "Otoa - GEN (DIF)",
    "Oyegoke - VER (DIF)",
    "Palestra - CAG (DIF)",
    "Parisi - FIO (DIF)",
    "Patric - LAZ (DIF)",
    "Paz Y. - SAS (DIF)",
    "Pedersen - TOR (DIF)",
    "Pellegrini Lu. - LAZ (DIF)",
    "Perez M. - LEC (DIF)",
    "Pezzella Giu. - CRE (DIF)",
    "Pieragnolo - SAS (DIF)",
    "Provstgaard - LAZ (DIF)",
    "Ramon - COM (DIF)",
    "Rensch - ROM (DIF)",
    "Rodriguez Ju. - CAG (DIF)",
    "Romagna - SAS (DIF)",
    "Romagnoli - LAZ (DIF)",
    "Rugani - JUV (DIF)",
    "Rui Modesto - UDI (DIF)",
    "Sabelli - GEN (DIF)",
    "Schuurs - TOR (DIF)",
    "Siebert - LEC (DIF)",
    "Slotsager - VER (DIF)",
    "Smolcic I. - COM (DIF)",
    "Tavares N. - LAZ (DIF)",
    "Terracciano F. - CRE (DIF)",
    "Tiago Gabriel - LEC (DIF)",
    "Troilo - PAR (DIF)",
    "Tsimikas - ROM (DIF)",
    "Valenti - PAR (DIF)",
    "Valentini N. - VER (DIF)",
    "Valeri - PAR (DIF)",
    "Valle - COM (DIF)",
    "Van Der Brempt - COM (DIF)",
    "Veiga D. - LEC (DIF)",
    "Vitik - BOL (DIF)",
    "Vojvoda - COM (DIF)",
    "Walukiewicz - SAS (DIF)",
    "Zanoli - UDI (DIF)",
    "Zappa - CAG (DIF)",
    "Zappacosta - ATA (DIF)",
    "Zatterstrom - GEN (DIF)",
    "Zemura - UDI (DIF)",
    "Ziolkowski - ROM (DIF)",
    "Zè Pedro - CAG (DIF)",
    "Adopo - CAG (CEN)",
    "Adzic - JUV (CEN)",
    "Aebischer - PIS (CEN)",
    "Akinsanmiro - PIS (CEN)",
    "Akpa Akpro - VER (CEN)",
    "Al-Musrati - VER (CEN)",
    "Amorim - GEN (CEN)",
    "Basic - LAZ (CEN)",
    "Belahyane - LAZ (CEN)",
    "Berisha M. - LEC (CEN)",
    "Bernede - VER (CEN)",
    "Boloca - SAS (CEN)",
    "Bondo - CRE (CEN)",
    "Caqueret - COM (CEN)",
    "Cataldi - LAZ (CEN)",
    "Collocolo - CRE (CEN)",
    "Cornet - GEN (CEN)",
    "Coulibaly L. - LEC (CEN)",
    "Cremaschi - PAR (CEN)",
    "Cuenca H. - GEN (CEN)",
    "Deiola - CAG (CEN)",
    "Dele-Bashiru - LAZ (CEN)",
    "Diouf - INT (CEN)",
    "El Aynaoui - ROM (CEN)",
    "Ekkelenkamp - UDI (CEN)",
    "Ellertsson - GEN (CEN)",
    "Elmas - NAP (CEN)",
    "Estevez - PAR (CEN)",
    "Fabbian - FIO (CEN)",
    "Fadera - SAS (CEN)",
    "Fazzini - FIO (CEN)",
    "Felici - CAG (CEN)",
    "Fofana Sa. - LEC (CEN)",
    "Fofana Y. - MIL (CEN)",
    "Frendrup - GEN (CEN)",
    "Gaetano - CAG (CEN)",
    "Gagliardini - VER (CEN)",
    "Gandelman - LEC (CEN)",
    "Gineitis - TOR (CEN)",
    "Gorter - LEC (CEN)",
    "Grassi - CRE (CEN)",
    "Harrison - FIO (CEN)",
    "Harroui - VER (CEN)",
    "Helgason - LEC (CEN)",
    "Hojholt - PIS (CEN)",
    "Iannoni - SAS (CEN)",
    "Ilic - TOR (CEN)",
    "Ilkhan - TOR (CEN)",
    "Jashari - MIL (CEN)",
    "Karlstrom - UDI (CEN)",
    "Kastanos - VER (CEN)",
    "Keita M. - PAR (CEN)",
    "Konè I. - SAS (CEN)",
    "Koopmeiners - JUV (CEN)",
    "Kostic - JUV (CEN)",
    "Leris - PIS (CEN)",
    "Lipani - SAS (CEN)",
    "Liteta - CAG (CEN)",
    "Lorran - PIS (CEN)",
    "Lovric - VER (CEN)",
    "Loyola - PIS (CEN)",
    "Luis Henrique - INT (CEN)",
    "Maleh - LEC (CEN)",
    "Malinovskyi - GEN (CEN)",
    "Marchwinski - LEC (CEN)",
    "Marin M. - PIS (CEN)",
    "Masini - GEN (CEN)",
    "Matic - SAS (CEN)",
    "Mazzitelli - CAG (CEN)",
    "McKennie - JUV (CEN)",
    "Miller L. - UDI (CEN)",
    "Miretti - JUV (CEN)",
    "Moro N. - BOL (CEN)",
    "Musah - ATA (CEN)",
    "Ndour - FIO (CEN)",
    "Neres - NAP (CEN)",
    "Ngom - LEC (CEN)",
    "Niasse - VER (CEN)",
    "Nicolussi Caviglia - PAR (CEN)",
    "Onana J. - GEN (CEN)",
    "Ondrejka - PAR (CEN)",
    "Ordonez C. - PAR (CEN)",
    "Payero - CRE (CEN)",
    "Pellegrini Lo. - ROM (CEN)",
    "Piccinini G. - PIS (CEN)",
    "Pierotti - LEC (CEN)",
    "Pierret - LEC (CEN)",
    "Piotrowski - UDI (CEN)",
    "Pisilli - ROM (CEN)",
    "Pobega - BOL (CEN)",
    "Prati - CAG (CEN)",
    "Ramadani - LEC (CEN)",
    "Rowe - BOL (CEN)",
    "Sabiri - FIO (CEN)",
    "Sala A. - LEC (CEN)",
    "Samardzic - ATA (CEN)",
    "Serdar - VER (CEN)",
    "Sergi Roberto - COM (CEN)",
    "Sohm - BOL (CEN)",
    "Sorensen O. - PAR (CEN)",
    "Sottil - LEC (CEN)",
    "Stengs - PIS (CEN)",
    "Sulemana I. - CAG (CEN)",
    "Suslov - VER (CEN)",
    "Tameze - TOR (CEN)",
    "Taylor K. - LAZ (CEN)",
    "Tete Morente - LEC (CEN)",
    "Thorsby - GEN (CEN)",
    "Thorstvedt - SAS (CEN)",
    "Tourè I. - PIS (CEN)",
    "Vandeputte - CRE (CEN)",
    "Vecino - LAZ (CEN)",
    "Venturino - ROM (CEN)",
    "Vergara - NAP (CEN)",
    "Volpato - SAS (CEN)",
    "Vranckx - SAS (CEN)",
    "Vural - PIS (CEN)",
    "Zalewski - ATA (CEN)",
    "Zambo Anguissa - NAP (CEN)",
    "Zarraga - UDI (CEN)",
    "Zerbin - CRE (CEN)",
    "Zhegrova - JUV (CEN)",
    "Zielinski - INT (CEN)",
    "Aboukhlal - TOR (ATT)",
    "Addai - COM (ATT)",
    "Albarracin - CAG (ATT)",
    "Ambrosino - NAP (ATT)",
    "Arena A. - ROM (ATT)",
    "Balentien - MIL (ATT)",
    "Bayo V. - UDI (ATT)",
    "Belotti - CAG (ATT)",
    "Benedyczak - PAR (ATT)",
    "Bonazzoli - CRE (ATT)",
    "Bonny - INT (ATT)",
    "Borrelli - CAG (ATT)",
    "Buffon L. - PIS (ATT)",
    "Buksa - UDI (ATT)",
    "Cambiaghi - BOL (ATT)",
    "Camarda - LEC (ATT)",
    "Cancellieri - LAZ (ATT)",
    "Cheddira - LEC (ATT)",
    "Dia - LAZ (ATT)",
    "Diao - COM (ATT)",
    "Djuric - CRE (ATT)",
    "Dominguez B. - BOL (ATT)",
    "Dovbyk - ROM (ATT)",
    "Durosinmi - PIS (ATT)",
    "Ekhator - GEN (ATT)",
    "Ekuban - GEN (ATT)",
    "Elphege - PAR (ATT)",
    "Esposito F.P. - INT (ATT)",
    "Ferguson E. - ROM (ATT)",
    "Frigan - PAR (ATT)",
    "Fullkrug - MIL (ATT)",
    "Gimenez - MIL (ATT)",
    "Giovane - NAP (ATT)",
    "Gueye - UDI (ATT)",
    "Immobile - BOL (ATT)",
    "Isaac - VER (ATT)",
    "Johnsen - CRE (ATT)",
    "Kilicsoy - CAG (ATT)",
    "Kouamè - FIO (ATT)",
    "Lukaku - NAP (ATT)",
    "Luvumbo - CAG (ATT)",
    "Malen - ROM (ATT)",
    "Meister - PIS (ATT)",
    "Milik - JUV (ATT)",
    "Moreo - PIS (ATT)",
    "Moro L. - SAS (ATT)",
    "Mosquera - VER (ATT)",
    "Moumbagna - CRE (ATT)",
    "N'Dri - LEC (ATT)",
    "Njie - TOR (ATT)",
    "Noslin - LAZ (ATT)",
    "Nzola - PIS (ATT)",
    "Okereke - CRE (ATT)",
    "Openda - JUV (ATT)",
    "Orban G. - VER (ATT)",
    "Pavoletti - CAG (ATT)",
    "Pedro - LAZ (ATT)",
    "Pierini - SAS (ATT)",
    "Raspadori - ATA (ATT)",
    "Ratkov - LAZ (ATT)",
    "Sanabria - CRE (ATT)",
    "Sarr A. - VER (ATT)",
    "Skjellerup - SAS (ATT)",
    "Solomon - FIO (ATT)",
    "Stojilkovic - PIS (ATT)",
    "Stulic - LEC (ATT)",
    "Sulemana K. - ATA (ATT)",
    "Trepy - CAG (ATT)",
    "Vaz - ROM (ATT)",
    "Vitinha O. - GEN (ATT)",
    "Zapata D. - TOR (ATT)",
]
